name: Update IPs

on:
  schedule:
    - cron: '*/50 * * * *'
  push:
    branches:
      - main

jobs:
  update_ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run update_ips.py
        run: python update_ips.py

      - name: Check if there are changes
        run: |
          if ! git diff --exit-code; then
            git config --global user.name 'GrahLnn'
            git config --global user.email 'grahlnn@skiff.com'
            git add best_ips.txt
            git commit -m 'Update IPs'
            git push
          else
            echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
